version: '3'
networks:
  development:
services:
  wardu_redis:
    image: redis:7.0-alpine
    command: redis-server
    networks:
      - development
    volumes:
      - shared_data:/var/shared/redis
    ports:
      - 6379:6379
  wardu_db:
    image: postgres:14.2-alpine
    container_name: wardu_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5099:5432
  wardu_app:
    image: registry.chibi.rodeo/wardu:latest
    container_name: wardu_app
    volumes:
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://wardu_redis:6379/0
      DATABASE_HOST: wardu_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: wardu_development
    depends_on:
      - wardu_db
      - wardu_redis

volumes:
  db_data:
  gem_cache:
  shared_data:
